<ns0:svg xmlns:ns0="http://www.w3.org/2000/svg" xmlns:ns1="http://www.w3.org/1999/xlink" width="316pt" height="27pt" viewBox="0.00 0.00 316.00 27.00">
<ns0:g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 23)">
<ns0:title>inheritancefe9130ef2a</ns0:title>

<ns0:g id="node1" class="node">
<ns0:title>ContextExistsInLibraryError</ns0:title>
<ns0:g id="a_node1"><ns0:a ns1:href="../pyVHDLModel/pyVHDLModel.Exception.html#pyVHDLModel.Exception.ContextExistsInLibraryError" ns1:title="This exception is raised, when the context already existing in the library." target="_top">
<ns0:polygon fill="white" stroke="#1e90ff" points="308,-19 158,-19 158,0 308,0 308,-19" />
<ns0:text text-anchor="middle" x="233" y="-7" font-family="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans" font-size="10.00">ContextExistsInLibraryError</ns0:text>
</ns0:a>
</ns0:g>
</ns0:g>

<ns0:g id="node2" class="node">
<ns0:title>VHDLModelException</ns0:title>
<ns0:g id="a_node2"><ns0:a ns1:href="../pyVHDLModel/pyVHDLModel.Exception.html#pyVHDLModel.Exception.VHDLModelException" ns1:title="Base-class for all exceptions (errors) raised by pyVHDLModel." target="_top">
<ns0:polygon fill="white" stroke="#1e90ff" points="122,-19 0,-19 0,0 122,0 122,-19" />
<ns0:text text-anchor="middle" x="61" y="-7" font-family="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans" font-size="10.00">VHDLModelException</ns0:text>
</ns0:a>
</ns0:g>
</ns0:g>

<ns0:g id="edge1" class="edge">
<ns0:title>VHDLModelException-&gt;ContextExistsInLibraryError</ns0:title>
<ns0:path fill="none" stroke="black" stroke-width="0.5" d="M122.41,-9.5C132.26,-9.5 142.58,-9.5 152.79,-9.5" />
<ns0:polygon fill="black" stroke="black" stroke-width="0.5" points="152.79,-11.25 157.79,-9.5 152.79,-7.75 152.79,-11.25" />
</ns0:g>
</ns0:g>
</ns0:svg>